version: '3.9'
services:                  
    postgres:
          container_name: reward_db
          restart: always
          image: postgres:latest
          ports:
            - 7132:5432
          volumes:
            - /data/rewarddb/postgres
          environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: Aa.12345@
            POSTGRES_DB: rewarddb
          networks:
            - prod

                           
    web-api:
        build: ./
        restart: always
        depends_on:
            - postgres
        environment:
            ASPNETCORE_ENVIRONMENT: Prod
        networks:
            - prod
        ports: 
            - 7130:80

networks:
    prod:
